version: "3.6"

services:
  master:
    build:
      context: .
      target: master
    command: ["/app/master"]
    ports:
      - "1234:1234"

  cs1:
    build:
      context: .
      target: chunkserver
    command: [ "/app/chunkserver" ]
    environment:
      SERVER_HOST: cs1
      SERVER_PORT: 50001
      MASTER_ADDR: "master:1234"
    depends_on:
      - master
    ports:
      - "1235:50001"

  cs2:
    build:
      context: .
      target: chunkserver
    command: [ "/app/chunkserver" ]
    environment:
      SERVER_HOST: cs2
      SERVER_PORT: 50002
      MASTER_ADDR: "master:1234"
    depends_on:
      - master
    ports:
      - "1236:50002"

  cs3:
    build:
      context: .
      target: chunkserver
    command: [ "/app/chunkserver" ]
    environment:
      SERVER_HOST: cs3
      SERVER_PORT: 50003
      MASTER_ADDR: "master:1234"
    depends_on:
      - master
    ports:
      - "1237:50003"

  cs4:
    build:
      context: .
      target: chunkserver
    command: [ "/app/chunkserver" ]
    environment:
      SERVER_HOST: cs4
      SERVER_PORT: 50004
      MASTER_ADDR: "master:1234"
    depends_on:
      - master
    ports:
      - "1238:50004"
